spring.application.name=travel-planner

spring.datasource.url=jdbc:postgresql://localhost:5432/travelplanner
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=bXlTdXBlclNlY3JldEtleUZvckp3dFRva2VuU2lnbmluZ1RoYXRJc0xvbmdFbm91Z2g=
app.jwt.expiration-ms=600000

restcountries.api.base-url=https://restcountries.com/v3.1
restcountries.api.fields=name,capital,region,subregion,population,currencies,flags,latlng
